"""AUTO-GENERATED STUBS FOR IDE AUTOCOMPLETE. DO NOT EDIT."""
from typing import Tuple, Any

class NNTensorStubs:
    def TargetedTensor(self, *args, **kwargs) -> 'Any': ...
    def Tensor(self, *args, **kwargs) -> 'Any': ...
    def ax(self, *args, **kwargs) -> 'Any': ...
    def Tie(self, *args, **kwargs) -> 'Any': ...
    def axiom_nn_op(self, *args, **kwargs) -> 'Any': ...
    def layer_norm(self, *args, **kwargs) -> 'Any': ...
    def rms_norm(self, *args, **kwargs) -> 'Any': ...
    def reinforce(self, *args, **kwargs) -> 'Any': ...
    def gelu(self, *args, **kwargs) -> 'Any': ...
    def silu(self, *args, **kwargs) -> 'Any': ...
    def swish(self, *args, **kwargs) -> 'Any': ...
    def mish(self, *args, **kwargs) -> 'Any': ...
    def relu(self, *args, **kwargs) -> 'Any': ...
    def leaky_relu(self, *args, **kwargs) -> 'Any': ...
    def sigmoid(self, *args, **kwargs) -> 'Any': ...
    def tanh(self, *args, **kwargs) -> 'Any': ...
    def softplus(self, *args, **kwargs) -> 'Any': ...
    def log_sigmoid(self, *args, **kwargs) -> 'Any': ...
    def exp(self, *args, **kwargs) -> 'Any': ...
    def clip(self, *args, **kwargs) -> 'Any': ...
    def clamp(self, *args, **kwargs) -> 'Any': ...
    def softmax(self, *args, **kwargs) -> 'Any': ...
    def log_softmax(self, *args, **kwargs) -> 'Any': ...

class NNTargetedTensorStubs:
    def TargetedTensor(self, *args, **kwargs) -> 'Any': ...
    def Tensor(self, *args, **kwargs) -> 'Any': ...
    def ax(self, *args, **kwargs) -> 'Any': ...
    def Tie(self, *args, **kwargs) -> 'Any': ...
    def axiom_nn_op(self, *args, **kwargs) -> 'Any': ...
    def layer_norm(self, *args, **kwargs) -> 'Any': ...
    def rms_norm(self, *args, **kwargs) -> 'Any': ...
    def reinforce(self, *args, **kwargs) -> 'Any': ...
    def gelu(self, *args, **kwargs) -> 'Any': ...
    def silu(self, *args, **kwargs) -> 'Any': ...
    def swish(self, *args, **kwargs) -> 'Any': ...
    def mish(self, *args, **kwargs) -> 'Any': ...
    def relu(self, *args, **kwargs) -> 'Any': ...
    def leaky_relu(self, *args, **kwargs) -> 'Any': ...
    def sigmoid(self, *args, **kwargs) -> 'Any': ...
    def tanh(self, *args, **kwargs) -> 'Any': ...
    def softplus(self, *args, **kwargs) -> 'Any': ...
    def log_sigmoid(self, *args, **kwargs) -> 'Any': ...
    def exp(self, *args, **kwargs) -> 'Any': ...
    def clip(self, *args, **kwargs) -> 'Any': ...
    def clamp(self, *args, **kwargs) -> 'Any': ...
    def softmax(self, *args, **kwargs) -> 'Any': ...
    def log_softmax(self, *args, **kwargs) -> 'Any': ...

class NNTargetedBundleStubs:
    def TargetedTensor(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def Tensor(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ax(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def Tie(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def axiom_nn_op(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def layer_norm(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def rms_norm(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def reinforce(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def gelu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def silu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def swish(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def mish(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def relu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def leaky_relu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sigmoid(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def tanh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def softplus(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def log_sigmoid(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def exp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def clip(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def clamp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def softmax(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def log_softmax(self, *args, **kwargs) -> Tuple['Any', ...]: ...
