"""AUTO-GENERATED STUBS FOR IDE AUTOCOMPLETE. DO NOT EDIT."""
from typing import Tuple, Any

class NNTensorStubs:
    def ComplexWarning(self, *args, **kwargs) -> 'Any': ...
    def TargetedTensor(self, *args, **kwargs) -> 'Any': ...
    def Tensor(self, *args, **kwargs) -> 'Any': ...
    def Tie(self, *args, **kwargs) -> 'Any': ...
    def abs(self, *args, **kwargs) -> 'Any': ...
    def absolute(self, *args, **kwargs) -> 'Any': ...
    def acos(self, *args, **kwargs) -> 'Any': ...
    def acosh(self, *args, **kwargs) -> 'Any': ...
    def add(self, *args, **kwargs) -> 'Any': ...
    def all(self, *args, **kwargs) -> 'Any': ...
    def allclose(self, *args, **kwargs) -> 'Any': ...
    def amax(self, *args, **kwargs) -> 'Any': ...
    def amin(self, *args, **kwargs) -> 'Any': ...
    def angle(self, *args, **kwargs) -> 'Any': ...
    def any(self, *args, **kwargs) -> 'Any': ...
    def apply_along_axis(self, *args, **kwargs) -> 'Any': ...
    def apply_over_axes(self, *args, **kwargs) -> 'Any': ...
    def arange(self, *args, **kwargs) -> 'Any': ...
    def arccos(self, *args, **kwargs) -> 'Any': ...
    def arccosh(self, *args, **kwargs) -> 'Any': ...
    def arcsin(self, *args, **kwargs) -> 'Any': ...
    def arcsinh(self, *args, **kwargs) -> 'Any': ...
    def arctan(self, *args, **kwargs) -> 'Any': ...
    def arctan2(self, *args, **kwargs) -> 'Any': ...
    def arctanh(self, *args, **kwargs) -> 'Any': ...
    def argmax(self, *args, **kwargs) -> 'Any': ...
    def argmin(self, *args, **kwargs) -> 'Any': ...
    def argpartition(self, *args, **kwargs) -> 'Any': ...
    def argsort(self, *args, **kwargs) -> 'Any': ...
    def around(self, *args, **kwargs) -> 'Any': ...
    def array_equal(self, *args, **kwargs) -> 'Any': ...
    def array_equiv(self, *args, **kwargs) -> 'Any': ...
    def array_repr(self, *args, **kwargs) -> 'Any': ...
    def array_split(self, *args, **kwargs) -> 'Any': ...
    def array_str(self, *args, **kwargs) -> 'Any': ...
    def asin(self, *args, **kwargs) -> 'Any': ...
    def asinh(self, *args, **kwargs) -> 'Any': ...
    def astype(self, *args, **kwargs) -> 'Any': ...
    def atan(self, *args, **kwargs) -> 'Any': ...
    def atan2(self, *args, **kwargs) -> 'Any': ...
    def atanh(self, *args, **kwargs) -> 'Any': ...
    def atleast_1d(self, *args, **kwargs) -> 'Any': ...
    def atleast_2d(self, *args, **kwargs) -> 'Any': ...
    def atleast_3d(self, *args, **kwargs) -> 'Any': ...
    def average(self, *args, **kwargs) -> 'Any': ...
    def axiom_nn_op(self, *args, **kwargs) -> 'Any': ...
    def bartlett(self, *args, **kwargs) -> 'Any': ...
    def bfloat16(self, *args, **kwargs) -> 'Any': ...
    def bincount(self, *args, **kwargs) -> 'Any': ...
    def bitwise_and(self, *args, **kwargs) -> 'Any': ...
    def bitwise_count(self, *args, **kwargs) -> 'Any': ...
    def bitwise_invert(self, *args, **kwargs) -> 'Any': ...
    def bitwise_left_shift(self, *args, **kwargs) -> 'Any': ...
    def bitwise_not(self, *args, **kwargs) -> 'Any': ...
    def bitwise_or(self, *args, **kwargs) -> 'Any': ...
    def bitwise_right_shift(self, *args, **kwargs) -> 'Any': ...
    def bitwise_xor(self, *args, **kwargs) -> 'Any': ...
    def blackman(self, *args, **kwargs) -> 'Any': ...
    def block(self, *args, **kwargs) -> 'Any': ...
    def bool(self, *args, **kwargs) -> 'Any': ...
    def bool_(self, *args, **kwargs) -> 'Any': ...
    def broadcast_arrays(self, *args, **kwargs) -> 'Any': ...
    def broadcast_shapes(self, *args, **kwargs) -> 'Any': ...
    def broadcast_to(self, *args, **kwargs) -> 'Any': ...
    def can_cast(self, *args, **kwargs) -> 'Any': ...
    def cbrt(self, *args, **kwargs) -> 'Any': ...
    def cdouble(self, *args, **kwargs) -> 'Any': ...
    def ceil(self, *args, **kwargs) -> 'Any': ...
    def celu(self, *args, **kwargs) -> 'Any': ...
    def character(self, *args, **kwargs) -> 'Any': ...
    def clamp(self, *args, **kwargs) -> 'Any': ...
    def clip(self, *args, **kwargs) -> 'Any': ...
    def complex128(self, *args, **kwargs) -> 'Any': ...
    def complex64(self, *args, **kwargs) -> 'Any': ...
    def complex_(self, *args, **kwargs) -> 'Any': ...
    def complexfloating(self, *args, **kwargs) -> 'Any': ...
    def compress(self, *args, **kwargs) -> 'Any': ...
    def concat(self, *args, **kwargs) -> 'Any': ...
    def conj(self, *args, **kwargs) -> 'Any': ...
    def conjugate(self, *args, **kwargs) -> 'Any': ...
    def convolve(self, *args, **kwargs) -> 'Any': ...
    def copysign(self, *args, **kwargs) -> 'Any': ...
    def corrcoef(self, *args, **kwargs) -> 'Any': ...
    def correlate(self, *args, **kwargs) -> 'Any': ...
    def cos(self, *args, **kwargs) -> 'Any': ...
    def cosh(self, *args, **kwargs) -> 'Any': ...
    def count_nonzero(self, *args, **kwargs) -> 'Any': ...
    def cov(self, *args, **kwargs) -> 'Any': ...
    def cross(self, *args, **kwargs) -> 'Any': ...
    def csingle(self, *args, **kwargs) -> 'Any': ...
    def cumprod(self, *args, **kwargs) -> 'Any': ...
    def cumsum(self, *args, **kwargs) -> 'Any': ...
    def cumulative_prod(self, *args, **kwargs) -> 'Any': ...
    def cumulative_sum(self, *args, **kwargs) -> 'Any': ...
    def deg2rad(self, *args, **kwargs) -> 'Any': ...
    def degrees(self, *args, **kwargs) -> 'Any': ...
    def diag_indices(self, *args, **kwargs) -> 'Any': ...
    def diag_indices_from(self, *args, **kwargs) -> 'Any': ...
    def diagflat(self, *args, **kwargs) -> 'Any': ...
    def diff(self, *args, **kwargs) -> 'Any': ...
    def digitize(self, *args, **kwargs) -> 'Any': ...
    def divide(self, *args, **kwargs) -> 'Any': ...
    def divmod(self, *args, **kwargs) -> 'Any': ...
    def dot(self, *args, **kwargs) -> 'Any': ...
    def dot_product_attention(self, *args, **kwargs) -> 'Any': ...
    def double(self, *args, **kwargs) -> 'Any': ...
    def dsplit(self, *args, **kwargs) -> 'Any': ...
    def dtype(self, *args, **kwargs) -> 'Any': ...
    def ediff1d(self, *args, **kwargs) -> 'Any': ...
    def einsum(self, *args, **kwargs) -> 'Any': ...
    def einsum_path(self, *args, **kwargs) -> 'Any': ...
    def elu(self, *args, **kwargs) -> 'Any': ...
    def equal(self, *args, **kwargs) -> 'Any': ...
    def exp(self, *args, **kwargs) -> 'Any': ...
    def exp2(self, *args, **kwargs) -> 'Any': ...
    def expm1(self, *args, **kwargs) -> 'Any': ...
    def extract(self, *args, **kwargs) -> 'Any': ...
    def eye(self, *args, **kwargs) -> 'Any': ...
    def fabs(self, *args, **kwargs) -> 'Any': ...
    def fill_diagonal(self, *args, **kwargs) -> 'Any': ...
    def finfo(self, *args, **kwargs) -> 'Any': ...
    def flatnonzero(self, *args, **kwargs) -> 'Any': ...
    def flexible(self, *args, **kwargs) -> 'Any': ...
    def flip(self, *args, **kwargs) -> 'Any': ...
    def fliplr(self, *args, **kwargs) -> 'Any': ...
    def flipud(self, *args, **kwargs) -> 'Any': ...
    def float16(self, *args, **kwargs) -> 'Any': ...
    def float32(self, *args, **kwargs) -> 'Any': ...
    def float4_e2m1fn(self, *args, **kwargs) -> 'Any': ...
    def float64(self, *args, **kwargs) -> 'Any': ...
    def float8_e3m4(self, *args, **kwargs) -> 'Any': ...
    def float8_e4m3(self, *args, **kwargs) -> 'Any': ...
    def float8_e4m3b11fnuz(self, *args, **kwargs) -> 'Any': ...
    def float8_e4m3fn(self, *args, **kwargs) -> 'Any': ...
    def float8_e4m3fnuz(self, *args, **kwargs) -> 'Any': ...
    def float8_e5m2(self, *args, **kwargs) -> 'Any': ...
    def float8_e5m2fnuz(self, *args, **kwargs) -> 'Any': ...
    def float8_e8m0fnu(self, *args, **kwargs) -> 'Any': ...
    def float_(self, *args, **kwargs) -> 'Any': ...
    def float_power(self, *args, **kwargs) -> 'Any': ...
    def floating(self, *args, **kwargs) -> 'Any': ...
    def floor(self, *args, **kwargs) -> 'Any': ...
    def floor_divide(self, *args, **kwargs) -> 'Any': ...
    def fmax(self, *args, **kwargs) -> 'Any': ...
    def fmin(self, *args, **kwargs) -> 'Any': ...
    def fmod(self, *args, **kwargs) -> 'Any': ...
    def frexp(self, *args, **kwargs) -> 'Any': ...
    def from_dlpack(self, *args, **kwargs) -> 'Any': ...
    def frombuffer(self, *args, **kwargs) -> 'Any': ...
    def fromfile(self, *args, **kwargs) -> 'Any': ...
    def fromfunction(self, *args, **kwargs) -> 'Any': ...
    def fromiter(self, *args, **kwargs) -> 'Any': ...
    def frompyfunc(self, *args, **kwargs) -> 'Any': ...
    def fromstring(self, *args, **kwargs) -> 'Any': ...
    def gcd(self, *args, **kwargs) -> 'Any': ...
    def gelu(self, *args, **kwargs) -> 'Any': ...
    def generic(self, *args, **kwargs) -> 'Any': ...
    def geomspace(self, *args, **kwargs) -> 'Any': ...
    def get_printoptions(self, *args, **kwargs) -> 'Any': ...
    def get_scaled_dot_general_config(self, *args, **kwargs) -> 'Any': ...
    def glu(self, *args, **kwargs) -> 'Any': ...
    def gradient(self, *args, **kwargs) -> 'Any': ...
    def greater(self, *args, **kwargs) -> 'Any': ...
    def greater_equal(self, *args, **kwargs) -> 'Any': ...
    def hamming(self, *args, **kwargs) -> 'Any': ...
    def hanning(self, *args, **kwargs) -> 'Any': ...
    def hard_sigmoid(self, *args, **kwargs) -> 'Any': ...
    def hard_silu(self, *args, **kwargs) -> 'Any': ...
    def hard_swish(self, *args, **kwargs) -> 'Any': ...
    def hard_tanh(self, *args, **kwargs) -> 'Any': ...
    def heaviside(self, *args, **kwargs) -> 'Any': ...
    def histogram(self, *args, **kwargs) -> 'Any': ...
    def histogram2d(self, *args, **kwargs) -> 'Any': ...
    def histogram_bin_edges(self, *args, **kwargs) -> 'Any': ...
    def histogramdd(self, *args, **kwargs) -> 'Any': ...
    def hsplit(self, *args, **kwargs) -> 'Any': ...
    def hypot(self, *args, **kwargs) -> 'Any': ...
    def i0(self, *args, **kwargs) -> 'Any': ...
    def identity(self, *args, **kwargs) -> 'Any': ...
    def iinfo(self, *args, **kwargs) -> 'Any': ...
    def imag(self, *args, **kwargs) -> 'Any': ...
    def indices(self, *args, **kwargs) -> 'Any': ...
    def inexact(self, *args, **kwargs) -> 'Any': ...
    def inner(self, *args, **kwargs) -> 'Any': ...
    def int16(self, *args, **kwargs) -> 'Any': ...
    def int2(self, *args, **kwargs) -> 'Any': ...
    def int32(self, *args, **kwargs) -> 'Any': ...
    def int4(self, *args, **kwargs) -> 'Any': ...
    def int64(self, *args, **kwargs) -> 'Any': ...
    def int8(self, *args, **kwargs) -> 'Any': ...
    def int_(self, *args, **kwargs) -> 'Any': ...
    def integer(self, *args, **kwargs) -> 'Any': ...
    def interp(self, *args, **kwargs) -> 'Any': ...
    def intersect1d(self, *args, **kwargs) -> 'Any': ...
    def invert(self, *args, **kwargs) -> 'Any': ...
    def isclose(self, *args, **kwargs) -> 'Any': ...
    def iscomplex(self, *args, **kwargs) -> 'Any': ...
    def iscomplexobj(self, *args, **kwargs) -> 'Any': ...
    def isdtype(self, *args, **kwargs) -> 'Any': ...
    def isfinite(self, *args, **kwargs) -> 'Any': ...
    def isin(self, *args, **kwargs) -> 'Any': ...
    def isinf(self, *args, **kwargs) -> 'Any': ...
    def isnan(self, *args, **kwargs) -> 'Any': ...
    def isneginf(self, *args, **kwargs) -> 'Any': ...
    def isposinf(self, *args, **kwargs) -> 'Any': ...
    def isreal(self, *args, **kwargs) -> 'Any': ...
    def isrealobj(self, *args, **kwargs) -> 'Any': ...
    def isscalar(self, *args, **kwargs) -> 'Any': ...
    def issubdtype(self, *args, **kwargs) -> 'Any': ...
    def iterable(self, *args, **kwargs) -> 'Any': ...
    def ix_(self, *args, **kwargs) -> 'Any': ...
    def kaiser(self, *args, **kwargs) -> 'Any': ...
    def kron(self, *args, **kwargs) -> 'Any': ...
    def layer_norm(self, *args, **kwargs) -> 'Any': ...
    def lcm(self, *args, **kwargs) -> 'Any': ...
    def ldexp(self, *args, **kwargs) -> 'Any': ...
    def leaky_relu(self, *args, **kwargs) -> 'Any': ...
    def left_shift(self, *args, **kwargs) -> 'Any': ...
    def less(self, *args, **kwargs) -> 'Any': ...
    def less_equal(self, *args, **kwargs) -> 'Any': ...
    def lexsort(self, *args, **kwargs) -> 'Any': ...
    def linspace(self, *args, **kwargs) -> 'Any': ...
    def load(self, *args, **kwargs) -> 'Any': ...
    def log(self, *args, **kwargs) -> 'Any': ...
    def log10(self, *args, **kwargs) -> 'Any': ...
    def log1mexp(self, *args, **kwargs) -> 'Any': ...
    def log1p(self, *args, **kwargs) -> 'Any': ...
    def log2(self, *args, **kwargs) -> 'Any': ...
    def log_sigmoid(self, *args, **kwargs) -> 'Any': ...
    def log_softmax(self, *args, **kwargs) -> 'Any': ...
    def logaddexp(self, *args, **kwargs) -> 'Any': ...
    def logaddexp2(self, *args, **kwargs) -> 'Any': ...
    def logical_and(self, *args, **kwargs) -> 'Any': ...
    def logical_not(self, *args, **kwargs) -> 'Any': ...
    def logical_or(self, *args, **kwargs) -> 'Any': ...
    def logical_xor(self, *args, **kwargs) -> 'Any': ...
    def logmeanexp(self, *args, **kwargs) -> 'Any': ...
    def logspace(self, *args, **kwargs) -> 'Any': ...
    def logsumexp(self, *args, **kwargs) -> 'Any': ...
    def mask_indices(self, *args, **kwargs) -> 'Any': ...
    def matmul(self, *args, **kwargs) -> 'Any': ...
    def matrix_transpose(self, *args, **kwargs) -> 'Any': ...
    def matvec(self, *args, **kwargs) -> 'Any': ...
    def median(self, *args, **kwargs) -> 'Any': ...
    def meshgrid(self, *args, **kwargs) -> 'Any': ...
    def mish(self, *args, **kwargs) -> 'Any': ...
    def mod(self, *args, **kwargs) -> 'Any': ...
    def modf(self, *args, **kwargs) -> 'Any': ...
    def multiply(self, *args, **kwargs) -> 'Any': ...
    def nan_to_num(self, *args, **kwargs) -> 'Any': ...
    def nanargmax(self, *args, **kwargs) -> 'Any': ...
    def nanargmin(self, *args, **kwargs) -> 'Any': ...
    def nancumprod(self, *args, **kwargs) -> 'Any': ...
    def nancumsum(self, *args, **kwargs) -> 'Any': ...
    def nanmax(self, *args, **kwargs) -> 'Any': ...
    def nanmean(self, *args, **kwargs) -> 'Any': ...
    def nanmedian(self, *args, **kwargs) -> 'Any': ...
    def nanmin(self, *args, **kwargs) -> 'Any': ...
    def nanpercentile(self, *args, **kwargs) -> 'Any': ...
    def nanprod(self, *args, **kwargs) -> 'Any': ...
    def nanquantile(self, *args, **kwargs) -> 'Any': ...
    def nanstd(self, *args, **kwargs) -> 'Any': ...
    def nansum(self, *args, **kwargs) -> 'Any': ...
    def nanvar(self, *args, **kwargs) -> 'Any': ...
    def ndarray(self, *args, **kwargs) -> 'Any': ...
    def negative(self, *args, **kwargs) -> 'Any': ...
    def nextafter(self, *args, **kwargs) -> 'Any': ...
    def nonzero(self, *args, **kwargs) -> 'Any': ...
    def not_equal(self, *args, **kwargs) -> 'Any': ...
    def number(self, *args, **kwargs) -> 'Any': ...
    def object_(self, *args, **kwargs) -> 'Any': ...
    def one_hot(self, *args, **kwargs) -> 'Any': ...
    def outer(self, *args, **kwargs) -> 'Any': ...
    def packbits(self, *args, **kwargs) -> 'Any': ...
    def partition(self, *args, **kwargs) -> 'Any': ...
    def percentile(self, *args, **kwargs) -> 'Any': ...
    def permute_dims(self, *args, **kwargs) -> 'Any': ...
    def piecewise(self, *args, **kwargs) -> 'Any': ...
    def place(self, *args, **kwargs) -> 'Any': ...
    def poly(self, *args, **kwargs) -> 'Any': ...
    def polyadd(self, *args, **kwargs) -> 'Any': ...
    def polyder(self, *args, **kwargs) -> 'Any': ...
    def polydiv(self, *args, **kwargs) -> 'Any': ...
    def polyfit(self, *args, **kwargs) -> 'Any': ...
    def polyint(self, *args, **kwargs) -> 'Any': ...
    def polymul(self, *args, **kwargs) -> 'Any': ...
    def polysub(self, *args, **kwargs) -> 'Any': ...
    def polyval(self, *args, **kwargs) -> 'Any': ...
    def positive(self, *args, **kwargs) -> 'Any': ...
    def pow(self, *args, **kwargs) -> 'Any': ...
    def power(self, *args, **kwargs) -> 'Any': ...
    def printoptions(self, *args, **kwargs) -> 'Any': ...
    def prod(self, *args, **kwargs) -> 'Any': ...
    def promote_types(self, *args, **kwargs) -> 'Any': ...
    def ptp(self, *args, **kwargs) -> 'Any': ...
    def put_along_axis(self, *args, **kwargs) -> 'Any': ...
    def quantile(self, *args, **kwargs) -> 'Any': ...
    def rad2deg(self, *args, **kwargs) -> 'Any': ...
    def radians(self, *args, **kwargs) -> 'Any': ...
    def ravel(self, *args, **kwargs) -> 'Any': ...
    def ravel_multi_index(self, *args, **kwargs) -> 'Any': ...
    def real(self, *args, **kwargs) -> 'Any': ...
    def reciprocal(self, *args, **kwargs) -> 'Any': ...
    def reinforce(self, *args, **kwargs) -> 'Any': ...
    def relu(self, *args, **kwargs) -> 'Any': ...
    def relu6(self, *args, **kwargs) -> 'Any': ...
    def remainder(self, *args, **kwargs) -> 'Any': ...
    def result_type(self, *args, **kwargs) -> 'Any': ...
    def right_shift(self, *args, **kwargs) -> 'Any': ...
    def rint(self, *args, **kwargs) -> 'Any': ...
    def rms_norm(self, *args, **kwargs) -> 'Any': ...
    def roll(self, *args, **kwargs) -> 'Any': ...
    def roots(self, *args, **kwargs) -> 'Any': ...
    def rot90(self, *args, **kwargs) -> 'Any': ...
    def round(self, *args, **kwargs) -> 'Any': ...
    def save(self, *args, **kwargs) -> 'Any': ...
    def savez(self, *args, **kwargs) -> 'Any': ...
    def scaled_dot_general(self, *args, **kwargs) -> 'Any': ...
    def scaled_matmul(self, *args, **kwargs) -> 'Any': ...
    def searchsorted(self, *args, **kwargs) -> 'Any': ...
    def select(self, *args, **kwargs) -> 'Any': ...
    def selu(self, *args, **kwargs) -> 'Any': ...
    def set_printoptions(self, *args, **kwargs) -> 'Any': ...
    def setdiff1d(self, *args, **kwargs) -> 'Any': ...
    def setxor1d(self, *args, **kwargs) -> 'Any': ...
    def sigmoid(self, *args, **kwargs) -> 'Any': ...
    def sign(self, *args, **kwargs) -> 'Any': ...
    def signbit(self, *args, **kwargs) -> 'Any': ...
    def signedinteger(self, *args, **kwargs) -> 'Any': ...
    def silu(self, *args, **kwargs) -> 'Any': ...
    def sin(self, *args, **kwargs) -> 'Any': ...
    def sinc(self, *args, **kwargs) -> 'Any': ...
    def single(self, *args, **kwargs) -> 'Any': ...
    def sinh(self, *args, **kwargs) -> 'Any': ...
    def soft_sign(self, *args, **kwargs) -> 'Any': ...
    def softmax(self, *args, **kwargs) -> 'Any': ...
    def softplus(self, *args, **kwargs) -> 'Any': ...
    def sort(self, *args, **kwargs) -> 'Any': ...
    def sort_complex(self, *args, **kwargs) -> 'Any': ...
    def spacing(self, *args, **kwargs) -> 'Any': ...
    def sparse_plus(self, *args, **kwargs) -> 'Any': ...
    def sparse_sigmoid(self, *args, **kwargs) -> 'Any': ...
    def sqrt(self, *args, **kwargs) -> 'Any': ...
    def square(self, *args, **kwargs) -> 'Any': ...
    def squareplus(self, *args, **kwargs) -> 'Any': ...
    def ssm_op(self, *args, **kwargs) -> 'Any': ...
    def standardize(self, *args, **kwargs) -> 'Any': ...
    def std(self, *args, **kwargs) -> 'Any': ...
    def subtract(self, *args, **kwargs) -> 'Any': ...
    def swish(self, *args, **kwargs) -> 'Any': ...
    def take_along_axis(self, *args, **kwargs) -> 'Any': ...
    def tan(self, *args, **kwargs) -> 'Any': ...
    def tanh(self, *args, **kwargs) -> 'Any': ...
    def tensordot(self, *args, **kwargs) -> 'Any': ...
    def trace(self, *args, **kwargs) -> 'Any': ...
    def trapezoid(self, *args, **kwargs) -> 'Any': ...
    def tri(self, *args, **kwargs) -> 'Any': ...
    def tril(self, *args, **kwargs) -> 'Any': ...
    def tril_indices(self, *args, **kwargs) -> 'Any': ...
    def tril_indices_from(self, *args, **kwargs) -> 'Any': ...
    def trim_zeros(self, *args, **kwargs) -> 'Any': ...
    def triu(self, *args, **kwargs) -> 'Any': ...
    def triu_indices(self, *args, **kwargs) -> 'Any': ...
    def triu_indices_from(self, *args, **kwargs) -> 'Any': ...
    def true_divide(self, *args, **kwargs) -> 'Any': ...
    def trunc(self, *args, **kwargs) -> 'Any': ...
    def ufunc(self, *args, **kwargs) -> 'Any': ...
    def uint(self, *args, **kwargs) -> 'Any': ...
    def uint16(self, *args, **kwargs) -> 'Any': ...
    def uint2(self, *args, **kwargs) -> 'Any': ...
    def uint32(self, *args, **kwargs) -> 'Any': ...
    def uint4(self, *args, **kwargs) -> 'Any': ...
    def uint64(self, *args, **kwargs) -> 'Any': ...
    def uint8(self, *args, **kwargs) -> 'Any': ...
    def union1d(self, *args, **kwargs) -> 'Any': ...
    def unique(self, *args, **kwargs) -> 'Any': ...
    def unique_all(self, *args, **kwargs) -> 'Any': ...
    def unique_counts(self, *args, **kwargs) -> 'Any': ...
    def unique_inverse(self, *args, **kwargs) -> 'Any': ...
    def unique_values(self, *args, **kwargs) -> 'Any': ...
    def unpackbits(self, *args, **kwargs) -> 'Any': ...
    def unravel_index(self, *args, **kwargs) -> 'Any': ...
    def unsignedinteger(self, *args, **kwargs) -> 'Any': ...
    def unstack(self, *args, **kwargs) -> 'Any': ...
    def vander(self, *args, **kwargs) -> 'Any': ...
    def var(self, *args, **kwargs) -> 'Any': ...
    def vdot(self, *args, **kwargs) -> 'Any': ...
    def vecdot(self, *args, **kwargs) -> 'Any': ...
    def vecmat(self, *args, **kwargs) -> 'Any': ...
    def vectorize(self, *args, **kwargs) -> 'Any': ...
    def vsplit(self, *args, **kwargs) -> 'Any': ...

class NNTargetedTensorStubs:
    def ComplexWarning(self, *args, **kwargs) -> 'Any': ...
    def TargetedTensor(self, *args, **kwargs) -> 'Any': ...
    def Tensor(self, *args, **kwargs) -> 'Any': ...
    def Tie(self, *args, **kwargs) -> 'Any': ...
    def abs(self, *args, **kwargs) -> 'Any': ...
    def absolute(self, *args, **kwargs) -> 'Any': ...
    def acos(self, *args, **kwargs) -> 'Any': ...
    def acosh(self, *args, **kwargs) -> 'Any': ...
    def add(self, *args, **kwargs) -> 'Any': ...
    def all(self, *args, **kwargs) -> 'Any': ...
    def allclose(self, *args, **kwargs) -> 'Any': ...
    def amax(self, *args, **kwargs) -> 'Any': ...
    def amin(self, *args, **kwargs) -> 'Any': ...
    def angle(self, *args, **kwargs) -> 'Any': ...
    def any(self, *args, **kwargs) -> 'Any': ...
    def apply_along_axis(self, *args, **kwargs) -> 'Any': ...
    def apply_over_axes(self, *args, **kwargs) -> 'Any': ...
    def arange(self, *args, **kwargs) -> 'Any': ...
    def arccos(self, *args, **kwargs) -> 'Any': ...
    def arccosh(self, *args, **kwargs) -> 'Any': ...
    def arcsin(self, *args, **kwargs) -> 'Any': ...
    def arcsinh(self, *args, **kwargs) -> 'Any': ...
    def arctan(self, *args, **kwargs) -> 'Any': ...
    def arctan2(self, *args, **kwargs) -> 'Any': ...
    def arctanh(self, *args, **kwargs) -> 'Any': ...
    def argmax(self, *args, **kwargs) -> 'Any': ...
    def argmin(self, *args, **kwargs) -> 'Any': ...
    def argpartition(self, *args, **kwargs) -> 'Any': ...
    def argsort(self, *args, **kwargs) -> 'Any': ...
    def around(self, *args, **kwargs) -> 'Any': ...
    def array_equal(self, *args, **kwargs) -> 'Any': ...
    def array_equiv(self, *args, **kwargs) -> 'Any': ...
    def array_repr(self, *args, **kwargs) -> 'Any': ...
    def array_split(self, *args, **kwargs) -> 'Any': ...
    def array_str(self, *args, **kwargs) -> 'Any': ...
    def asin(self, *args, **kwargs) -> 'Any': ...
    def asinh(self, *args, **kwargs) -> 'Any': ...
    def astype(self, *args, **kwargs) -> 'Any': ...
    def atan(self, *args, **kwargs) -> 'Any': ...
    def atan2(self, *args, **kwargs) -> 'Any': ...
    def atanh(self, *args, **kwargs) -> 'Any': ...
    def atleast_1d(self, *args, **kwargs) -> 'Any': ...
    def atleast_2d(self, *args, **kwargs) -> 'Any': ...
    def atleast_3d(self, *args, **kwargs) -> 'Any': ...
    def average(self, *args, **kwargs) -> 'Any': ...
    def axiom_nn_op(self, *args, **kwargs) -> 'Any': ...
    def bartlett(self, *args, **kwargs) -> 'Any': ...
    def bfloat16(self, *args, **kwargs) -> 'Any': ...
    def bincount(self, *args, **kwargs) -> 'Any': ...
    def bitwise_and(self, *args, **kwargs) -> 'Any': ...
    def bitwise_count(self, *args, **kwargs) -> 'Any': ...
    def bitwise_invert(self, *args, **kwargs) -> 'Any': ...
    def bitwise_left_shift(self, *args, **kwargs) -> 'Any': ...
    def bitwise_not(self, *args, **kwargs) -> 'Any': ...
    def bitwise_or(self, *args, **kwargs) -> 'Any': ...
    def bitwise_right_shift(self, *args, **kwargs) -> 'Any': ...
    def bitwise_xor(self, *args, **kwargs) -> 'Any': ...
    def blackman(self, *args, **kwargs) -> 'Any': ...
    def block(self, *args, **kwargs) -> 'Any': ...
    def bool(self, *args, **kwargs) -> 'Any': ...
    def bool_(self, *args, **kwargs) -> 'Any': ...
    def broadcast_arrays(self, *args, **kwargs) -> 'Any': ...
    def broadcast_shapes(self, *args, **kwargs) -> 'Any': ...
    def broadcast_to(self, *args, **kwargs) -> 'Any': ...
    def can_cast(self, *args, **kwargs) -> 'Any': ...
    def cbrt(self, *args, **kwargs) -> 'Any': ...
    def cdouble(self, *args, **kwargs) -> 'Any': ...
    def ceil(self, *args, **kwargs) -> 'Any': ...
    def celu(self, *args, **kwargs) -> 'Any': ...
    def character(self, *args, **kwargs) -> 'Any': ...
    def clamp(self, *args, **kwargs) -> 'Any': ...
    def clip(self, *args, **kwargs) -> 'Any': ...
    def complex128(self, *args, **kwargs) -> 'Any': ...
    def complex64(self, *args, **kwargs) -> 'Any': ...
    def complex_(self, *args, **kwargs) -> 'Any': ...
    def complexfloating(self, *args, **kwargs) -> 'Any': ...
    def compress(self, *args, **kwargs) -> 'Any': ...
    def concat(self, *args, **kwargs) -> 'Any': ...
    def conj(self, *args, **kwargs) -> 'Any': ...
    def conjugate(self, *args, **kwargs) -> 'Any': ...
    def convolve(self, *args, **kwargs) -> 'Any': ...
    def copysign(self, *args, **kwargs) -> 'Any': ...
    def corrcoef(self, *args, **kwargs) -> 'Any': ...
    def correlate(self, *args, **kwargs) -> 'Any': ...
    def cos(self, *args, **kwargs) -> 'Any': ...
    def cosh(self, *args, **kwargs) -> 'Any': ...
    def count_nonzero(self, *args, **kwargs) -> 'Any': ...
    def cov(self, *args, **kwargs) -> 'Any': ...
    def cross(self, *args, **kwargs) -> 'Any': ...
    def csingle(self, *args, **kwargs) -> 'Any': ...
    def cumprod(self, *args, **kwargs) -> 'Any': ...
    def cumsum(self, *args, **kwargs) -> 'Any': ...
    def cumulative_prod(self, *args, **kwargs) -> 'Any': ...
    def cumulative_sum(self, *args, **kwargs) -> 'Any': ...
    def deg2rad(self, *args, **kwargs) -> 'Any': ...
    def degrees(self, *args, **kwargs) -> 'Any': ...
    def diag_indices(self, *args, **kwargs) -> 'Any': ...
    def diag_indices_from(self, *args, **kwargs) -> 'Any': ...
    def diagflat(self, *args, **kwargs) -> 'Any': ...
    def diff(self, *args, **kwargs) -> 'Any': ...
    def digitize(self, *args, **kwargs) -> 'Any': ...
    def divide(self, *args, **kwargs) -> 'Any': ...
    def divmod(self, *args, **kwargs) -> 'Any': ...
    def dot(self, *args, **kwargs) -> 'Any': ...
    def dot_product_attention(self, *args, **kwargs) -> 'Any': ...
    def double(self, *args, **kwargs) -> 'Any': ...
    def dsplit(self, *args, **kwargs) -> 'Any': ...
    def dtype(self, *args, **kwargs) -> 'Any': ...
    def ediff1d(self, *args, **kwargs) -> 'Any': ...
    def einsum(self, *args, **kwargs) -> 'Any': ...
    def einsum_path(self, *args, **kwargs) -> 'Any': ...
    def elu(self, *args, **kwargs) -> 'Any': ...
    def equal(self, *args, **kwargs) -> 'Any': ...
    def exp(self, *args, **kwargs) -> 'Any': ...
    def exp2(self, *args, **kwargs) -> 'Any': ...
    def expm1(self, *args, **kwargs) -> 'Any': ...
    def extract(self, *args, **kwargs) -> 'Any': ...
    def eye(self, *args, **kwargs) -> 'Any': ...
    def fabs(self, *args, **kwargs) -> 'Any': ...
    def fill_diagonal(self, *args, **kwargs) -> 'Any': ...
    def finfo(self, *args, **kwargs) -> 'Any': ...
    def flatnonzero(self, *args, **kwargs) -> 'Any': ...
    def flexible(self, *args, **kwargs) -> 'Any': ...
    def flip(self, *args, **kwargs) -> 'Any': ...
    def fliplr(self, *args, **kwargs) -> 'Any': ...
    def flipud(self, *args, **kwargs) -> 'Any': ...
    def float16(self, *args, **kwargs) -> 'Any': ...
    def float32(self, *args, **kwargs) -> 'Any': ...
    def float4_e2m1fn(self, *args, **kwargs) -> 'Any': ...
    def float64(self, *args, **kwargs) -> 'Any': ...
    def float8_e3m4(self, *args, **kwargs) -> 'Any': ...
    def float8_e4m3(self, *args, **kwargs) -> 'Any': ...
    def float8_e4m3b11fnuz(self, *args, **kwargs) -> 'Any': ...
    def float8_e4m3fn(self, *args, **kwargs) -> 'Any': ...
    def float8_e4m3fnuz(self, *args, **kwargs) -> 'Any': ...
    def float8_e5m2(self, *args, **kwargs) -> 'Any': ...
    def float8_e5m2fnuz(self, *args, **kwargs) -> 'Any': ...
    def float8_e8m0fnu(self, *args, **kwargs) -> 'Any': ...
    def float_(self, *args, **kwargs) -> 'Any': ...
    def float_power(self, *args, **kwargs) -> 'Any': ...
    def floating(self, *args, **kwargs) -> 'Any': ...
    def floor(self, *args, **kwargs) -> 'Any': ...
    def floor_divide(self, *args, **kwargs) -> 'Any': ...
    def fmax(self, *args, **kwargs) -> 'Any': ...
    def fmin(self, *args, **kwargs) -> 'Any': ...
    def fmod(self, *args, **kwargs) -> 'Any': ...
    def frexp(self, *args, **kwargs) -> 'Any': ...
    def from_dlpack(self, *args, **kwargs) -> 'Any': ...
    def frombuffer(self, *args, **kwargs) -> 'Any': ...
    def fromfile(self, *args, **kwargs) -> 'Any': ...
    def fromfunction(self, *args, **kwargs) -> 'Any': ...
    def fromiter(self, *args, **kwargs) -> 'Any': ...
    def frompyfunc(self, *args, **kwargs) -> 'Any': ...
    def fromstring(self, *args, **kwargs) -> 'Any': ...
    def gcd(self, *args, **kwargs) -> 'Any': ...
    def gelu(self, *args, **kwargs) -> 'Any': ...
    def generic(self, *args, **kwargs) -> 'Any': ...
    def geomspace(self, *args, **kwargs) -> 'Any': ...
    def get_printoptions(self, *args, **kwargs) -> 'Any': ...
    def get_scaled_dot_general_config(self, *args, **kwargs) -> 'Any': ...
    def glu(self, *args, **kwargs) -> 'Any': ...
    def gradient(self, *args, **kwargs) -> 'Any': ...
    def greater(self, *args, **kwargs) -> 'Any': ...
    def greater_equal(self, *args, **kwargs) -> 'Any': ...
    def hamming(self, *args, **kwargs) -> 'Any': ...
    def hanning(self, *args, **kwargs) -> 'Any': ...
    def hard_sigmoid(self, *args, **kwargs) -> 'Any': ...
    def hard_silu(self, *args, **kwargs) -> 'Any': ...
    def hard_swish(self, *args, **kwargs) -> 'Any': ...
    def hard_tanh(self, *args, **kwargs) -> 'Any': ...
    def heaviside(self, *args, **kwargs) -> 'Any': ...
    def histogram(self, *args, **kwargs) -> 'Any': ...
    def histogram2d(self, *args, **kwargs) -> 'Any': ...
    def histogram_bin_edges(self, *args, **kwargs) -> 'Any': ...
    def histogramdd(self, *args, **kwargs) -> 'Any': ...
    def hsplit(self, *args, **kwargs) -> 'Any': ...
    def hypot(self, *args, **kwargs) -> 'Any': ...
    def i0(self, *args, **kwargs) -> 'Any': ...
    def identity(self, *args, **kwargs) -> 'Any': ...
    def iinfo(self, *args, **kwargs) -> 'Any': ...
    def imag(self, *args, **kwargs) -> 'Any': ...
    def indices(self, *args, **kwargs) -> 'Any': ...
    def inexact(self, *args, **kwargs) -> 'Any': ...
    def inner(self, *args, **kwargs) -> 'Any': ...
    def int16(self, *args, **kwargs) -> 'Any': ...
    def int2(self, *args, **kwargs) -> 'Any': ...
    def int32(self, *args, **kwargs) -> 'Any': ...
    def int4(self, *args, **kwargs) -> 'Any': ...
    def int64(self, *args, **kwargs) -> 'Any': ...
    def int8(self, *args, **kwargs) -> 'Any': ...
    def int_(self, *args, **kwargs) -> 'Any': ...
    def integer(self, *args, **kwargs) -> 'Any': ...
    def interp(self, *args, **kwargs) -> 'Any': ...
    def intersect1d(self, *args, **kwargs) -> 'Any': ...
    def invert(self, *args, **kwargs) -> 'Any': ...
    def isclose(self, *args, **kwargs) -> 'Any': ...
    def iscomplex(self, *args, **kwargs) -> 'Any': ...
    def iscomplexobj(self, *args, **kwargs) -> 'Any': ...
    def isdtype(self, *args, **kwargs) -> 'Any': ...
    def isfinite(self, *args, **kwargs) -> 'Any': ...
    def isin(self, *args, **kwargs) -> 'Any': ...
    def isinf(self, *args, **kwargs) -> 'Any': ...
    def isnan(self, *args, **kwargs) -> 'Any': ...
    def isneginf(self, *args, **kwargs) -> 'Any': ...
    def isposinf(self, *args, **kwargs) -> 'Any': ...
    def isreal(self, *args, **kwargs) -> 'Any': ...
    def isrealobj(self, *args, **kwargs) -> 'Any': ...
    def isscalar(self, *args, **kwargs) -> 'Any': ...
    def issubdtype(self, *args, **kwargs) -> 'Any': ...
    def iterable(self, *args, **kwargs) -> 'Any': ...
    def ix_(self, *args, **kwargs) -> 'Any': ...
    def kaiser(self, *args, **kwargs) -> 'Any': ...
    def kron(self, *args, **kwargs) -> 'Any': ...
    def layer_norm(self, *args, **kwargs) -> 'Any': ...
    def lcm(self, *args, **kwargs) -> 'Any': ...
    def ldexp(self, *args, **kwargs) -> 'Any': ...
    def leaky_relu(self, *args, **kwargs) -> 'Any': ...
    def left_shift(self, *args, **kwargs) -> 'Any': ...
    def less(self, *args, **kwargs) -> 'Any': ...
    def less_equal(self, *args, **kwargs) -> 'Any': ...
    def lexsort(self, *args, **kwargs) -> 'Any': ...
    def linspace(self, *args, **kwargs) -> 'Any': ...
    def load(self, *args, **kwargs) -> 'Any': ...
    def log(self, *args, **kwargs) -> 'Any': ...
    def log10(self, *args, **kwargs) -> 'Any': ...
    def log1mexp(self, *args, **kwargs) -> 'Any': ...
    def log1p(self, *args, **kwargs) -> 'Any': ...
    def log2(self, *args, **kwargs) -> 'Any': ...
    def log_sigmoid(self, *args, **kwargs) -> 'Any': ...
    def log_softmax(self, *args, **kwargs) -> 'Any': ...
    def logaddexp(self, *args, **kwargs) -> 'Any': ...
    def logaddexp2(self, *args, **kwargs) -> 'Any': ...
    def logical_and(self, *args, **kwargs) -> 'Any': ...
    def logical_not(self, *args, **kwargs) -> 'Any': ...
    def logical_or(self, *args, **kwargs) -> 'Any': ...
    def logical_xor(self, *args, **kwargs) -> 'Any': ...
    def logmeanexp(self, *args, **kwargs) -> 'Any': ...
    def logspace(self, *args, **kwargs) -> 'Any': ...
    def logsumexp(self, *args, **kwargs) -> 'Any': ...
    def mask_indices(self, *args, **kwargs) -> 'Any': ...
    def matmul(self, *args, **kwargs) -> 'Any': ...
    def matrix_transpose(self, *args, **kwargs) -> 'Any': ...
    def matvec(self, *args, **kwargs) -> 'Any': ...
    def median(self, *args, **kwargs) -> 'Any': ...
    def meshgrid(self, *args, **kwargs) -> 'Any': ...
    def mish(self, *args, **kwargs) -> 'Any': ...
    def mod(self, *args, **kwargs) -> 'Any': ...
    def modf(self, *args, **kwargs) -> 'Any': ...
    def multiply(self, *args, **kwargs) -> 'Any': ...
    def nan_to_num(self, *args, **kwargs) -> 'Any': ...
    def nanargmax(self, *args, **kwargs) -> 'Any': ...
    def nanargmin(self, *args, **kwargs) -> 'Any': ...
    def nancumprod(self, *args, **kwargs) -> 'Any': ...
    def nancumsum(self, *args, **kwargs) -> 'Any': ...
    def nanmax(self, *args, **kwargs) -> 'Any': ...
    def nanmean(self, *args, **kwargs) -> 'Any': ...
    def nanmedian(self, *args, **kwargs) -> 'Any': ...
    def nanmin(self, *args, **kwargs) -> 'Any': ...
    def nanpercentile(self, *args, **kwargs) -> 'Any': ...
    def nanprod(self, *args, **kwargs) -> 'Any': ...
    def nanquantile(self, *args, **kwargs) -> 'Any': ...
    def nanstd(self, *args, **kwargs) -> 'Any': ...
    def nansum(self, *args, **kwargs) -> 'Any': ...
    def nanvar(self, *args, **kwargs) -> 'Any': ...
    def ndarray(self, *args, **kwargs) -> 'Any': ...
    def negative(self, *args, **kwargs) -> 'Any': ...
    def nextafter(self, *args, **kwargs) -> 'Any': ...
    def nonzero(self, *args, **kwargs) -> 'Any': ...
    def not_equal(self, *args, **kwargs) -> 'Any': ...
    def number(self, *args, **kwargs) -> 'Any': ...
    def object_(self, *args, **kwargs) -> 'Any': ...
    def one_hot(self, *args, **kwargs) -> 'Any': ...
    def outer(self, *args, **kwargs) -> 'Any': ...
    def packbits(self, *args, **kwargs) -> 'Any': ...
    def partition(self, *args, **kwargs) -> 'Any': ...
    def percentile(self, *args, **kwargs) -> 'Any': ...
    def permute_dims(self, *args, **kwargs) -> 'Any': ...
    def piecewise(self, *args, **kwargs) -> 'Any': ...
    def place(self, *args, **kwargs) -> 'Any': ...
    def poly(self, *args, **kwargs) -> 'Any': ...
    def polyadd(self, *args, **kwargs) -> 'Any': ...
    def polyder(self, *args, **kwargs) -> 'Any': ...
    def polydiv(self, *args, **kwargs) -> 'Any': ...
    def polyfit(self, *args, **kwargs) -> 'Any': ...
    def polyint(self, *args, **kwargs) -> 'Any': ...
    def polymul(self, *args, **kwargs) -> 'Any': ...
    def polysub(self, *args, **kwargs) -> 'Any': ...
    def polyval(self, *args, **kwargs) -> 'Any': ...
    def positive(self, *args, **kwargs) -> 'Any': ...
    def pow(self, *args, **kwargs) -> 'Any': ...
    def power(self, *args, **kwargs) -> 'Any': ...
    def printoptions(self, *args, **kwargs) -> 'Any': ...
    def prod(self, *args, **kwargs) -> 'Any': ...
    def promote_types(self, *args, **kwargs) -> 'Any': ...
    def ptp(self, *args, **kwargs) -> 'Any': ...
    def put_along_axis(self, *args, **kwargs) -> 'Any': ...
    def quantile(self, *args, **kwargs) -> 'Any': ...
    def rad2deg(self, *args, **kwargs) -> 'Any': ...
    def radians(self, *args, **kwargs) -> 'Any': ...
    def ravel(self, *args, **kwargs) -> 'Any': ...
    def ravel_multi_index(self, *args, **kwargs) -> 'Any': ...
    def real(self, *args, **kwargs) -> 'Any': ...
    def reciprocal(self, *args, **kwargs) -> 'Any': ...
    def reinforce(self, *args, **kwargs) -> 'Any': ...
    def relu(self, *args, **kwargs) -> 'Any': ...
    def relu6(self, *args, **kwargs) -> 'Any': ...
    def remainder(self, *args, **kwargs) -> 'Any': ...
    def result_type(self, *args, **kwargs) -> 'Any': ...
    def right_shift(self, *args, **kwargs) -> 'Any': ...
    def rint(self, *args, **kwargs) -> 'Any': ...
    def rms_norm(self, *args, **kwargs) -> 'Any': ...
    def roll(self, *args, **kwargs) -> 'Any': ...
    def roots(self, *args, **kwargs) -> 'Any': ...
    def rot90(self, *args, **kwargs) -> 'Any': ...
    def round(self, *args, **kwargs) -> 'Any': ...
    def save(self, *args, **kwargs) -> 'Any': ...
    def savez(self, *args, **kwargs) -> 'Any': ...
    def scaled_dot_general(self, *args, **kwargs) -> 'Any': ...
    def scaled_matmul(self, *args, **kwargs) -> 'Any': ...
    def searchsorted(self, *args, **kwargs) -> 'Any': ...
    def select(self, *args, **kwargs) -> 'Any': ...
    def selu(self, *args, **kwargs) -> 'Any': ...
    def set_printoptions(self, *args, **kwargs) -> 'Any': ...
    def setdiff1d(self, *args, **kwargs) -> 'Any': ...
    def setxor1d(self, *args, **kwargs) -> 'Any': ...
    def sigmoid(self, *args, **kwargs) -> 'Any': ...
    def sign(self, *args, **kwargs) -> 'Any': ...
    def signbit(self, *args, **kwargs) -> 'Any': ...
    def signedinteger(self, *args, **kwargs) -> 'Any': ...
    def silu(self, *args, **kwargs) -> 'Any': ...
    def sin(self, *args, **kwargs) -> 'Any': ...
    def sinc(self, *args, **kwargs) -> 'Any': ...
    def single(self, *args, **kwargs) -> 'Any': ...
    def sinh(self, *args, **kwargs) -> 'Any': ...
    def soft_sign(self, *args, **kwargs) -> 'Any': ...
    def softmax(self, *args, **kwargs) -> 'Any': ...
    def softplus(self, *args, **kwargs) -> 'Any': ...
    def sort(self, *args, **kwargs) -> 'Any': ...
    def sort_complex(self, *args, **kwargs) -> 'Any': ...
    def spacing(self, *args, **kwargs) -> 'Any': ...
    def sparse_plus(self, *args, **kwargs) -> 'Any': ...
    def sparse_sigmoid(self, *args, **kwargs) -> 'Any': ...
    def sqrt(self, *args, **kwargs) -> 'Any': ...
    def square(self, *args, **kwargs) -> 'Any': ...
    def squareplus(self, *args, **kwargs) -> 'Any': ...
    def ssm_op(self, *args, **kwargs) -> 'Any': ...
    def standardize(self, *args, **kwargs) -> 'Any': ...
    def std(self, *args, **kwargs) -> 'Any': ...
    def subtract(self, *args, **kwargs) -> 'Any': ...
    def swish(self, *args, **kwargs) -> 'Any': ...
    def take_along_axis(self, *args, **kwargs) -> 'Any': ...
    def tan(self, *args, **kwargs) -> 'Any': ...
    def tanh(self, *args, **kwargs) -> 'Any': ...
    def tensordot(self, *args, **kwargs) -> 'Any': ...
    def trace(self, *args, **kwargs) -> 'Any': ...
    def trapezoid(self, *args, **kwargs) -> 'Any': ...
    def tri(self, *args, **kwargs) -> 'Any': ...
    def tril(self, *args, **kwargs) -> 'Any': ...
    def tril_indices(self, *args, **kwargs) -> 'Any': ...
    def tril_indices_from(self, *args, **kwargs) -> 'Any': ...
    def trim_zeros(self, *args, **kwargs) -> 'Any': ...
    def triu(self, *args, **kwargs) -> 'Any': ...
    def triu_indices(self, *args, **kwargs) -> 'Any': ...
    def triu_indices_from(self, *args, **kwargs) -> 'Any': ...
    def true_divide(self, *args, **kwargs) -> 'Any': ...
    def trunc(self, *args, **kwargs) -> 'Any': ...
    def ufunc(self, *args, **kwargs) -> 'Any': ...
    def uint(self, *args, **kwargs) -> 'Any': ...
    def uint16(self, *args, **kwargs) -> 'Any': ...
    def uint2(self, *args, **kwargs) -> 'Any': ...
    def uint32(self, *args, **kwargs) -> 'Any': ...
    def uint4(self, *args, **kwargs) -> 'Any': ...
    def uint64(self, *args, **kwargs) -> 'Any': ...
    def uint8(self, *args, **kwargs) -> 'Any': ...
    def union1d(self, *args, **kwargs) -> 'Any': ...
    def unique(self, *args, **kwargs) -> 'Any': ...
    def unique_all(self, *args, **kwargs) -> 'Any': ...
    def unique_counts(self, *args, **kwargs) -> 'Any': ...
    def unique_inverse(self, *args, **kwargs) -> 'Any': ...
    def unique_values(self, *args, **kwargs) -> 'Any': ...
    def unpackbits(self, *args, **kwargs) -> 'Any': ...
    def unravel_index(self, *args, **kwargs) -> 'Any': ...
    def unsignedinteger(self, *args, **kwargs) -> 'Any': ...
    def unstack(self, *args, **kwargs) -> 'Any': ...
    def vander(self, *args, **kwargs) -> 'Any': ...
    def var(self, *args, **kwargs) -> 'Any': ...
    def vdot(self, *args, **kwargs) -> 'Any': ...
    def vecdot(self, *args, **kwargs) -> 'Any': ...
    def vecmat(self, *args, **kwargs) -> 'Any': ...
    def vectorize(self, *args, **kwargs) -> 'Any': ...
    def vsplit(self, *args, **kwargs) -> 'Any': ...

class NNTargetedBundleStubs:
    def ComplexWarning(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def TargetedTensor(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def Tensor(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def Tie(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def abs(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def absolute(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def acos(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def acosh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def add(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def all(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def allclose(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def amax(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def amin(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def angle(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def any(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def apply_along_axis(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def apply_over_axes(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def arange(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def arccos(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def arccosh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def arcsin(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def arcsinh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def arctan(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def arctan2(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def arctanh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def argmax(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def argmin(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def argpartition(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def argsort(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def around(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def array_equal(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def array_equiv(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def array_repr(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def array_split(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def array_str(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def asin(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def asinh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def astype(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def atan(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def atan2(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def atanh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def atleast_1d(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def atleast_2d(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def atleast_3d(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def average(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def axiom_nn_op(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bartlett(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bfloat16(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bincount(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bitwise_and(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bitwise_count(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bitwise_invert(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bitwise_left_shift(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bitwise_not(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bitwise_or(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bitwise_right_shift(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bitwise_xor(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def blackman(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def block(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bool(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def bool_(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def broadcast_arrays(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def broadcast_shapes(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def broadcast_to(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def can_cast(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def cbrt(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def cdouble(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ceil(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def celu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def character(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def clamp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def clip(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def complex128(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def complex64(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def complex_(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def complexfloating(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def compress(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def concat(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def conj(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def conjugate(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def convolve(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def copysign(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def corrcoef(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def correlate(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def cos(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def cosh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def count_nonzero(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def cov(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def cross(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def csingle(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def cumprod(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def cumsum(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def cumulative_prod(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def cumulative_sum(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def deg2rad(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def degrees(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def diag_indices(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def diag_indices_from(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def diagflat(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def diff(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def digitize(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def divide(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def divmod(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def dot(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def dot_product_attention(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def double(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def dsplit(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def dtype(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ediff1d(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def einsum(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def einsum_path(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def elu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def equal(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def exp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def exp2(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def expm1(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def extract(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def eye(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def fabs(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def fill_diagonal(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def finfo(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def flatnonzero(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def flexible(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def flip(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def fliplr(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def flipud(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float16(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float32(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float4_e2m1fn(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float64(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float8_e3m4(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float8_e4m3(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float8_e4m3b11fnuz(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float8_e4m3fn(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float8_e4m3fnuz(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float8_e5m2(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float8_e5m2fnuz(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float8_e8m0fnu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float_(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def float_power(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def floating(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def floor(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def floor_divide(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def fmax(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def fmin(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def fmod(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def frexp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def from_dlpack(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def frombuffer(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def fromfile(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def fromfunction(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def fromiter(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def frompyfunc(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def fromstring(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def gcd(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def gelu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def generic(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def geomspace(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def get_printoptions(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def get_scaled_dot_general_config(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def glu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def gradient(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def greater(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def greater_equal(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def hamming(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def hanning(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def hard_sigmoid(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def hard_silu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def hard_swish(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def hard_tanh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def heaviside(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def histogram(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def histogram2d(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def histogram_bin_edges(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def histogramdd(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def hsplit(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def hypot(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def i0(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def identity(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def iinfo(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def imag(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def indices(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def inexact(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def inner(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def int16(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def int2(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def int32(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def int4(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def int64(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def int8(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def int_(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def integer(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def interp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def intersect1d(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def invert(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isclose(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def iscomplex(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def iscomplexobj(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isdtype(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isfinite(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isin(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isinf(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isnan(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isneginf(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isposinf(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isreal(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isrealobj(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def isscalar(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def issubdtype(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def iterable(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ix_(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def kaiser(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def kron(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def layer_norm(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def lcm(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ldexp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def leaky_relu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def left_shift(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def less(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def less_equal(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def lexsort(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def linspace(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def load(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def log(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def log10(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def log1mexp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def log1p(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def log2(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def log_sigmoid(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def log_softmax(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def logaddexp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def logaddexp2(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def logical_and(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def logical_not(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def logical_or(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def logical_xor(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def logmeanexp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def logspace(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def logsumexp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def mask_indices(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def matmul(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def matrix_transpose(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def matvec(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def median(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def meshgrid(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def mish(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def mod(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def modf(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def multiply(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nan_to_num(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanargmax(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanargmin(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nancumprod(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nancumsum(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanmax(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanmean(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanmedian(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanmin(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanpercentile(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanprod(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanquantile(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanstd(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nansum(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nanvar(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ndarray(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def negative(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nextafter(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def nonzero(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def not_equal(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def number(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def object_(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def one_hot(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def outer(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def packbits(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def partition(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def percentile(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def permute_dims(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def piecewise(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def place(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def poly(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def polyadd(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def polyder(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def polydiv(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def polyfit(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def polyint(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def polymul(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def polysub(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def polyval(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def positive(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def pow(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def power(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def printoptions(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def prod(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def promote_types(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ptp(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def put_along_axis(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def quantile(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def rad2deg(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def radians(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ravel(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ravel_multi_index(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def real(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def reciprocal(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def reinforce(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def relu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def relu6(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def remainder(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def result_type(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def right_shift(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def rint(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def rms_norm(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def roll(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def roots(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def rot90(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def round(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def save(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def savez(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def scaled_dot_general(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def scaled_matmul(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def searchsorted(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def select(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def selu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def set_printoptions(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def setdiff1d(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def setxor1d(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sigmoid(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sign(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def signbit(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def signedinteger(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def silu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sin(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sinc(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def single(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sinh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def soft_sign(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def softmax(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def softplus(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sort(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sort_complex(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def spacing(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sparse_plus(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sparse_sigmoid(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def sqrt(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def square(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def squareplus(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ssm_op(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def standardize(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def std(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def subtract(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def swish(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def take_along_axis(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def tan(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def tanh(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def tensordot(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def trace(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def trapezoid(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def tri(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def tril(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def tril_indices(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def tril_indices_from(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def trim_zeros(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def triu(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def triu_indices(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def triu_indices_from(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def true_divide(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def trunc(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def ufunc(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def uint(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def uint16(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def uint2(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def uint32(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def uint4(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def uint64(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def uint8(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def union1d(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def unique(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def unique_all(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def unique_counts(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def unique_inverse(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def unique_values(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def unpackbits(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def unravel_index(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def unsignedinteger(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def unstack(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def vander(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def var(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def vdot(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def vecdot(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def vecmat(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def vectorize(self, *args, **kwargs) -> Tuple['Any', ...]: ...
    def vsplit(self, *args, **kwargs) -> Tuple['Any', ...]: ...
